modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/yourusername/InfinityStonesMod/issues"

[[mods]]
modId="infinitystones"
version="1.0.0"
displayName="Infinity Stones Mod"
updateJSONURL=""
displayURL=""
logoFile="infinitystones.png"
credits="Inspired by Marvel's Infinity Stones, Insane Craft, SkiddziePlays and Bionic YouTube content"
authors="replit_ai"
description='''
A Minecraft mod that introduces the Infinity Stones as craftable, powerful artifacts with unique gameplay mechanics. 
Includes content from Insane Craft and various YouTube creators like SkiddziePlays and Bionic.

The mod includes:
- Six Infinity Stones with unique abilities
- Infinity Gauntlet to wield multiple stones
- Custom dimensions accessible through the stones
- Various powerful items from Insane Craft series
- Special weapons and tools from YouTube creator content
'''

[[dependencies.infinitystones]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.infinitystones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"